AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cannabis Industry Research Agent - Container-based Lambda deployment'

Parameters:
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: 'Anthropic API key for Claude access'
  
  S3BucketName:
    Type: String
    Default: 'retail-data-bcgr'
    Description: 'S3 bucket for storing research findings'
  
  ScheduleExpression:
    Type: String
    Default: 'rate(8 hours)'
    Description: 'How often to run the research agent'
  
  ImageUri:
    Type: String
    Description: 'ECR image URI for the Lambda function'

Resources:
  # IAM Role for Lambda
  ResearchAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'

  # Lambda Function (Container-based)
  ResearchAgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-research-agent'
      Description: 'AI-powered cannabis industry research agent (container)'
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Role: !GetAtt ResearchAgentRole.Arn
      Timeout: 600
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
      Tags:
        - Key: Application
          Value: IndustryResearchAgent

  # EventBridge Rule for Research Scheduling
  ResearchScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-schedule'
      Description: 'Schedule for running the research agent'
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Id: ResearchAgentTarget
          Arn: !GetAtt ResearchAgentFunction.Arn
          Input: '{"mode": "research"}'

  # Permission for EventBridge to invoke Lambda (research)
  ResearchSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResearchAgentFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ResearchScheduleRule.Arn

  # EventBridge Rule for Monthly Archival (runs on 1st of each month)
  ArchivalScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-archival'
      Description: 'Monthly archival of research findings'
      ScheduleExpression: 'cron(0 6 1 * ? *)'  # 6am UTC on 1st of each month
      State: ENABLED
      Targets:
        - Id: ArchivalTarget
          Arn: !GetAtt ResearchAgentFunction.Arn
          Input: '{"mode": "archive", "delete_after_archive": false}'

  # Permission for EventBridge to invoke Lambda (archival)
  ArchivalSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResearchAgentFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ArchivalScheduleRule.Arn

  # CloudWatch Log Group
  ResearchAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResearchAgentFunction}'
      RetentionInDays: 30

Outputs:
  LambdaFunctionArn:
    Description: 'Lambda function ARN'
    Value: !GetAtt ResearchAgentFunction.Arn
  
  LambdaFunctionName:
    Description: 'Lambda function name'
    Value: !Ref ResearchAgentFunction
  
  ScheduleRuleArn:
    Description: 'EventBridge schedule rule ARN'
    Value: !GetAtt ResearchScheduleRule.Arn
  
  S3FindingsPath:
    Description: 'S3 path for research findings'
    Value: !Sub 's3://${S3BucketName}/research-findings/'
