AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cannabis Industry Research Agent - Autonomous AI monitoring system'

Parameters:
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: 'Anthropic API key for Claude access'
  
  S3BucketName:
    Type: String
    Default: 'retail-data-bcgr'
    Description: 'S3 bucket for storing research findings'
  
  ScheduleExpression:
    Type: String
    Default: 'rate(8 hours)'
    Description: 'How often to run the research agent (e.g., rate(8 hours), cron(0 8,16,22 * * ? *))'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # IAM Role for Lambda
  ResearchAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref AnthropicApiSecret

  # Secrets Manager for API Key
  AnthropicApiSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/anthropic-api-key'
      Description: 'Anthropic API key for Research Agent'
      SecretString: !Sub '{"api_key": "${AnthropicApiKey}"}'

  # Lambda Function
  ResearchAgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-research-agent'
      Description: 'AI-powered cannabis industry research agent'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ResearchAgentRole.Arn
      Timeout: 300  # 5 minutes
      MemorySize: 512
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          # Placeholder - actual code deployed via update
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Deploy actual code"}
      Tags:
        - Key: Application
          Value: IndustryResearchAgent
        - Key: Environment
          Value: !Ref Environment

  # EventBridge Rule for Scheduling
  ResearchScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-schedule'
      Description: 'Schedule for running the research agent'
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Id: ResearchAgentTarget
          Arn: !GetAtt ResearchAgentFunction.Arn

  # Permission for EventBridge to invoke Lambda
  ResearchSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResearchAgentFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ResearchScheduleRule.Arn

  # CloudWatch Log Group (with retention)
  ResearchAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResearchAgentFunction}'
      RetentionInDays: 30

  # SNS Topic for Alerts (optional)
  ResearchAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-alerts'
      DisplayName: 'Research Agent Alerts'

  # CloudWatch Alarm for Errors
  ResearchErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-errors'
      AlarmDescription: 'Alert when research agent encounters errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ResearchAgentFunction
      AlarmActions:
        - !Ref ResearchAlertTopic

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the Research Agent Lambda function'
    Value: !GetAtt ResearchAgentFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-lambda-arn'
  
  LambdaFunctionName:
    Description: 'Name of the Lambda function'
    Value: !Ref ResearchAgentFunction
  
  ScheduleRuleArn:
    Description: 'ARN of the EventBridge schedule rule'
    Value: !GetAtt ResearchScheduleRule.Arn
  
  S3FindingsPath:
    Description: 'S3 path where research findings are stored'
    Value: !Sub 's3://${S3BucketName}/research-findings/'
  
  AlertTopicArn:
    Description: 'ARN of the SNS topic for alerts'
    Value: !Ref ResearchAlertTopic
